name: generate ai wiki
on:
 issues:
    types: [closed]
 issue_comment:
    types: [edited,opened,closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ixxmu/turn-issues-to-posts-action@master
        with:
          branch: "master" # default to main
          dir: "docs" # default to _posts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          created_at: ${{ github.event.issue.created_at }}
          updated_at: ${{ github.event.issue.updated_at }}
          label_name: ${{ github.event.label.name }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          number: ${{ github.event.issue.number }}
          comment: ${{ github.event.comment.body }}
          actor: ${{ github.actor }}
